Finnhub API Key: bu0ggnv48v6qoj76f840
START_BALANCE: 100000
SLIPPAGE: 0.0005
VALID_CHARS: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXY0123456789!@#$%^&*()-_=+<>,./?:;{}[]`~
START_BALANCE: 100000